######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 4 13:10:08 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += edittreelevel.h treeitem.h treemodel.h
FORMS += edittreelevel.ui
SOURCES += edittreelevel.cpp treeitem.cpp treemodel.cpp main.cpp
LIBS += -lsqlite3
